name: Build & Deploy Quartz (root vault → qsrc/content)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (v22)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: Clone Quartz (pin release for stability)
        run: git clone --depth=1 --branch v4.5.2 https://github.com/jackyzha0/quartz.git qsrc

      - name: Install Quartz deps
        run: pnpm install --no-frozen-lockfile --dir qsrc

      - name: Copy root vault → qsrc/content
        run: |
          mkdir -p qsrc/content
          rsync -a \
            --include='*/' \
            --include='*.md' --include='*.markdown' \
            --include='*.png' --include='*.jpg' --include='*.jpeg' \
            --include='*.gif' --include='*.svg' --include='*.webp' \
            --include='*.pdf' \
            --exclude='.git/**' \
            --exclude='.github/**' \
            --exclude='node_modules/**' \
            --exclude='public/**' \
            --exclude='qsrc/**' \
            --exclude='README.md' \
            ./ qsrc/content/
          echo "Sample files:" && find qsrc/content -maxdepth 2 -type f | head -n 20

      - name: Remove any config that slipped into content (important)
        run: rm -f qsrc/content/quartz.config.* || true

      - name: Provide quartz.config.ts beside the CLI
        run: |
          # Prefer a config you keep at the repo root.
          if [ -f quartz.config.ts ]; then
            cp quartz.config.ts qsrc/quartz.config.ts
          else
            # Write a safe default without using heredocs (avoids YAML/Bash EOF issues)
            mkdir -p qsrc
            printf '%s\n' \
'export default {' \
'  site: {' \
'    title: "Illumine",' \
'    description: "Spiritual wiki",' \
'    baseUrl: "https://benfreking123.github.io/Illumine/",' \
'  },' \
'  build: {' \
'    outputDir: "public",' \
'    ignorePatterns: ['"'"'**/.obsidian/**'"'"','"'"'**/qsrc/**'"'"'],' \
'    assetsDir: "static",' \
'  },' \
'  theme: {' \
'    css: ["./static/custom.css"],' \
'  },' \
'  plugins: {},' \
'}' > qsrc/quartz.config.ts
          fi
          mkdir -p qsrc/static
          [ -f qsrc/static/custom.css ] || printf '%s\n' '/* custom styles */' > qsrc/static/custom.css
          echo "Using config:"
          head -n 50 qsrc/quartz.config.ts

      - name: Build with Quartz CLI (run inside qsrc/, no --config flag)
        working-directory: qsrc
        run: node quartz/bootstrap-cli.mjs build

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: qsrc/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
