name: Build & Deploy Quartz (root vault → Quartz/content)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (v22)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: Clone Quartz (pin version)
        run: |
          git clone --depth=1 --branch v4.5.2 https://github.com/jackyzha0/quartz.git qsrc

      - name: Install Quartz deps (pnpm workspace)
        run: pnpm install --no-frozen-lockfile --dir qsrc

      - name: Approve pnpm build scripts (sharp, esbuild, etc.)
        working-directory: qsrc
        run: pnpm approve-builds

      - name: Copy root vault → qsrc/content
        run: |
          mkdir -p qsrc/content
          rsync -a \
            --include='*/' \
            --include='*.md' --include='*.markdown' \
            --include='*.png' --include='*.jpg' --include='*.jpeg' \
            --include='*.gif' --include='*.svg' --include='*.webp' \
            --include='*.pdf' \
            --exclude='.git/**' \
            --exclude='.github/**' \
            --exclude='node_modules/**' \
            --exclude='public/**' \
            --exclude='qsrc/**' \
            --exclude='README.md' \
            ./ qsrc/content/
          echo "Sample files:" && find qsrc/content -maxdepth 2 -type f | head -n 20

      - name: Remove any stray config inside content (important)
        run: |
          rm -f qsrc/content/quartz.config.ts qsrc/content/quartz.config.js qsrc/content/quartz.config.mjs || true

      - name: Provide quartz.config.ts beside the CLI
        run: |
          # Use your repo-root config if present…
          if [ -f quartz.config.ts ]; then
            cp quartz.config.ts qsrc/quartz.config.ts
          else
            # …otherwise write a minimal, safe default.
            cat > qsrc/quartz.config.ts <<'EOF'
export default {
  site: {
    title: "Illumine",
    description: "Spiritual wiki",
    baseUrl: "https://benfreking123.github.io/Illumine/",
  },
  build: {
    outputDir: "public",
    ignorePatterns: [],      // keep defined so Quartz won’t crash
    assetsDir: "static",
  },
  theme: {
    css: ["./static/custom.css"],
  },
  plugins: {},
}
EOF
          fi

          # Ensure a static dir so the CSS include doesn't 404.
          mkdir -p qsrc/static
          [ -f qsrc/static/custom.css ] || echo "/* custom styles */" > qsrc/static/custom.css

          echo "Using config at qsrc/quartz.config.ts:"
          head -n 40 qsrc/quartz.config.ts || true

      - name: Build with Quartz CLI (no --config flag)
        working-directory: qsrc
        run: node quartz/bootstrap-cli.mjs build

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: qsrc/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
