name: Build & Deploy Quartz (copy root -> /content)

on:
  push:
    branches: [ main ]        # or [ v4 ] if you prefer

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (v22) and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Enable corepack (pnpm)
        run: corepack enable

      # 1) Copy your ROOT vault into /content on the runner
      - name: Prepare /content from repo root
        run: |
          mkdir -p content
          rsync -a \
            --include='*/' \
            --include='*.md' --include='*.markdown' \
            --include='*.png' --include='*.jpg' --include='*.jpeg' \
            --include='*.gif' --include='*.svg' --include='*.webp' \
            --include='*.pdf' \
            --exclude='.git/**' \
            --exclude='.github/**' \
            --exclude='node_modules/**' \
            --exclude='public/**' \
            --exclude='quartz/**' \
            --exclude='content/**' \
            --exclude='README.md' \
            ./ ./content/
      - name: Show a few files in /content (debug)
        run: |
          echo "Top of /content:"
          find content -maxdepth 2 -type f | head -n 30

      # 2) Clone Quartz and install deps (pnpm workspace)
      - name: Clone Quartz
        run: git clone --depth=1 https://github.com/jackyzha0/quartz.git quartz

      - name: Install Quartz dependencies (pnpm workspace)
        run: pnpm install --no-frozen-lockfile --dir quartz

      # 3) Build via Quartz CLI entrypoint (bin -> ./quartz/bootstrap-cli.mjs)
      #    We call it directly instead of npx so we don't depend on a package name.
      - name: Build site with Quartz CLI
        run: node ./quartz/bootstrap-cli.mjs build

      # 4) Upload build artifact for Pages
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
