name: Build & Deploy Quartz

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Corepack
        run: corepack enable

      - name: Clone Quartz
        run: git clone --depth=1 --branch v4.5.2 https://github.com/jackyzha0/quartz.git qsrc

      - name: Install deps
        run: pnpm install --no-frozen-lockfile --dir qsrc

      - name: Approve build scripts
        working-directory: qsrc
        run: pnpm approve-builds || true

      - name: Copy vault
        run: |
          mkdir -p qsrc/content
          rsync -a \
            --include='*/' \
            --include='*.md' --include='*.markdown' \
            --include='*.png' --include='*.jpg' --include='*.jpeg' \
            --include='*.gif' --include='*.svg' --include='*.webp' \
            --include='*.pdf' \
            --exclude='.git/**' \
            --exclude='.github/**' \
            --exclude='node_modules/**' \
            --exclude='public/**' \
            --exclude='qsrc/**' \
            --exclude='README.md' \
            ./ qsrc/content/
          rm -f qsrc/content/quartz.config.ts qsrc/content/quartz.config.js qsrc/content/quartz.config.mjs

      - name: Provide config
        run: |
          if [ -f quartz.config.ts ]; then
            cp quartz.config.ts qsrc/quartz.config.ts
          else
            printf "%s" "export default {
  site: {
    title: \"Illumine\",
    description: \"Spiritual wiki\",
    baseUrl: \"https://benfreking123.github.io/Illumine/\"
  },
  build: {
    outputDir: \"public\",
    ignorePatterns: [],
    assetsDir: \"static\"
  },
  theme: { css: [\"./static/custom.css\"] },
  plugins: {}
}
" > qsrc/quartz.config.ts
          fi
          mkdir -p qsrc/static
          [ -f qsrc/static/custom.css ] || printf "/* custom styles */" > qsrc/static/custom.css

      - name: Build
        working-directory: qsrc
        run: node quartz/bootstrap-cli.mjs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: qsrc/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
